blank_issues_enabled: false
contact_links:
  - name: Stevie's Discord
    url: https://discord.gg/CcJeR3V5TQ
    about: Ask questions, receive support, and discuss with the community in our Discord server.
